# Project information
site_name: Kubernetes Workshop
site_author: Natron Tech GmbH
site_description: >-
  Documentation and guides for the Kubernetes Workshop by Natron Tech GmbH.

# Repository
repo_url: https://github.com/natrongmbh/kubernetes-workshop
repo_name: natrongmbh/kubernetes-workshop
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 Natron Tech GmbH

# Configuration
theme:
  favicon: assets/images/logo_natron_kubernetes.png
  logo: assets/images/logo_natron_kubernetes.png
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
  - search:
      lang: en

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/natrongmbh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/natron-gmbh

# Page tree
nav:
  - Home: index.md
  - Setup:
    - Client setup:
      - setup/client-setup/index.md
      - Linux: setup/client-setup/linux.md
      - Windows: setup/client-setup/windows.md
      - Mac OS: setup/client-setup/macos.md
      - Verify: setup/client-setup/verify.md
    - Tools:
      - setup/tools/index.md
  - Kubernetes Basics:
    - Introduction:
      - kubernetes-basics/introduction/index.md
      - YAML: kubernetes-basics/introduction/yaml.md
    - First Steps: kubernetes-basics/first-steps.md
    - Deploying Containers: kubernetes-basics/deploying-containers.md
    - Exposing Services: kubernetes-basics/exposing-services.md
    - Scaling Applications: kubernetes-basics/scaling-applications.md
    - Troubleshooting: kubernetes-basics/troubleshooting.md
    - Database Connection: kubernetes-basics/database-connection.md
    - Storage: kubernetes-basics/storage.md
    - Advanced Concepts:
      - kubernetes-basics/advanced-concepts/index.md
      - StatefulSets: kubernetes-basics/advanced-concepts/statefulsets.md
      - DaemonSets: kubernetes-basics/advanced-concepts/daemonsets.md
      - Jobs and CronJobs: kubernetes-basics/advanced-concepts/jobs-and-cronjobs.md
      - ConfigMaps: kubernetes-basics/advanced-concepts/configmaps.md
      - ResourceQuotas and Limits: kubernetes-basics/advanced-concepts/resource-quotas.md
      - Init Containers: kubernetes-basics/advanced-concepts/init-containers.md
      - Sidecars: kubernetes-basics/advanced-concepts/sidecars.md
    - Security: 
      - kubernetes-basics/security/index.md
      - RBAC: kubernetes-basics/security/rbac.md
      - Network Policies: kubernetes-basics/security/network-policies.md
      - Security Contexts: kubernetes-basics/security/security-contexts.md
    - Deployment Strategies: 
      - kubernetes-basics/deployment-strategies/index.md
    - Helm:
      - kubernetes-basics/helm/index.md
      - Helm Charts: kubernetes-basics/helm/helm-charts.md
    - Kustomize: 
      - kubernetes-basics/kustomize/index.md
  - Monitoring: monitoring/index.md
  - GitOps: gitops/index.md
  - Materials:
    - materials/index.md
    - Credits: materials/credits.md
  # - Labs:

# Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
