apiVersion: batch/v1
kind: Job
metadata:
  name: pg-dump
spec:
  template:
    spec:
      containers:
      - name: pg-dump
        image: postgres:14.5
        command: 
        - 'bash'
        - '-eo'
        - 'pipefail'
        - '-c'
        - >
          trap "echo Backup failed; exit 0" ERR;
          FILENAME=backup-$(date +%Y-%m-%d_%H-%M-%S).sql.gz;
          echo "creating .pgpass file";
          echo "$POSTGRES_HOST:$POSTGRES_PORT:$POSTGRES_DB:$POSTGRES_USER:$POSTGRES_PASSWORD" > ~/.pgpass;
          chmod 0600 ~/.pgpass;
          echo "creating dump";
          pg_dump -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER $POSTGRES_DB | gzip > $FILENAME;
          echo "";
          echo "Backup created: $FILENAME"; du -h $FILENAME;
        env:
        - name: POSTGRES_USER
          value: "<postgresql user>"
        - name: POSTGRES_HOST
          value: "<postgresql host>"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "<postgresql database>"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: job-secret
              key: POSTGRES_PASSWORD
        resources:
          limits:
            cpu: 40m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      restartPolicy: Never